FIX: Fix missing Slic3r::intersection declaration
/run/build/BambuStudio/src/slic3r/GUI/ImGuiWrapper.cpp: In static member function ‘static ImVec2 Slic3r::GUI::ImGuiWrapper::suggest_location(const ImVec2&, const Slic3r::Polygon&, const ImVec2&)’:
/run/build/BambuStudio/src/slic3r/GUI/ImGuiWrapper.cpp:2201: error: ‘intersection’ is not a member of ‘Slic3r’; did you mean ‘PrinterFunction’?
 2201 |         if (Slic3r::intersection(interest, Polygon(moved_polygon)).empty())

(cherry picked from commit de2b5b74cecda595d75fef894da4a92936e0cb7f)